import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, Clock } from "lucide-react";
import fertilityLab from "@/assets/fertility-lab.jpg";
import pregnancyCare from "@/assets/pregnancy-care.jpg";
import consultation from "@/assets/consultation.jpg";
import clinicInterior from "@/assets/clinic-interior.jpg";
import { AppointmentBand, PageHero, SectionHeading } from "@/components/PageSections";
import { Reveal } from "@/components/Reveal";
import { Button } from "@/components/ui/button";

export const Route=createFileRoute("/blog")({head:()=>({meta:[{title:"Fertility & Women's Health Insights | Dr. Priyanka Singh"},{name:"description",content:"Practical, doctor-led guidance on fertility, pregnancy, PCOS and women's wellbeing."},{property:"og:title",content:"Women's Health Insights | Dr. Priyanka Singh"},{property:"og:description",content:"Clear, reliable guidance for fertility, pregnancy and lifelong health."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/blog"}]}),component:BlogPage});
const posts=[{image:fertilityLab,category:"Fertility",title:"When should you consult a fertility specialist?",text:"Understand timelines, warning signs and what to expect from a first assessment."},{image:pregnancyCare,category:"Pregnancy",title:"A calm guide to your first trimester",text:"The appointments, scans and everyday changes that matter in the first 12 weeks."},{image:consultation,category:"PCOS",title:"PCOS care beyond the prescription",text:"How sleep, nutrition, movement and medical care work together over time."},{image:clinicInterior,category:"Women's health",title:"Preparing for your gynecology visit",text:"What to note, what to bring and the questions worth asking your doctor."}];
function BlogPage(){return <main><PageHero eyebrow="Health journal" title="Clear answers for informed choices." text="Doctor-led reading on fertility, pregnancy and women’s health—written to help you understand what comes next." image={clinicInterior} imageAlt="Peaceful women's health clinic"/><section className="py-20"><div className="mx-auto max-w-7xl px-5"><SectionHeading eyebrow="Latest insights" title="Read at your own pace" text="Practical guidance to help you prepare for conversations with your doctor."/><div className="mt-12 grid gap-7 md:grid-cols-2">{posts.map((p,i)=><Reveal key={p.title} delay={i*80}><article className="group overflow-hidden rounded-lg border border-border bg-card shadow-card-soft"><img src={p.image} alt="" className="aspect-16/9 w-full object-cover transition-transform duration-500 group-hover:scale-105"/><div className="p-7"><div className="flex items-center gap-3 text-xs font-semibold uppercase text-rose"><BookOpen className="h-4 w-4"/>{p.category}<span className="flex items-center gap-1 text-muted-foreground"><Clock className="h-3.5 w-3.5"/>4 min read</span></div><h2 className="mt-4 font-display text-2xl font-semibold text-wine">{p.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{p.text}</p><Button asChild variant="link" className="mt-4 px-0"><Link to="/contact">Ask Dr. Priyanka<ArrowRight/></Link></Button></div></article></Reveal>)}</div></div></section><AppointmentBand title="Have a question about your health?" text="Online and in-clinic consultations are available for personal guidance based on your history."/></main>}