import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, Clock, MapPin, MessageCircle, Phone, Video } from "lucide-react";
import clinicInterior from "@/assets/clinic-interior.jpg";
import consultation from "@/assets/consultation.jpg";
import { IconCard, PageHero, SectionHeading } from "@/components/PageSections";
import { Reveal } from "@/components/Reveal";
import { Button } from "@/components/ui/button";

export const Route=createFileRoute("/contact")({head:()=>({meta:[{title:"Book an Appointment | Dr. Priyanka Singh"},{name:"description",content:"Book an in-clinic or video consultation with Dr. Priyanka Singh at Radiance Speciality Clinics, Bachupally."},{property:"og:title",content:"Book an Appointment with Dr. Priyanka Singh"},{property:"og:description",content:"Contact Radiance Speciality Clinics for fertility, pregnancy and gynecology care."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/contact"}]}),component:ContactPage});
function ContactPage(){return <main><PageHero eyebrow="Contact & appointments" title="Your next step starts with a conversation." text="Choose an in-clinic appointment or video consultation. Our team will help you find a convenient time." image={consultation} imageAlt="Private consultation room"/><section className="py-20"><div className="mx-auto max-w-7xl px-5"><SectionHeading eyebrow="Get in touch" title="Choose what works for you"/><div className="mt-12 grid gap-6 md:grid-cols-3"><Reveal><IconCard icon={<Phone/>} title="Call the clinic" text="Speak with our team at +91 79955 74432 to arrange your visit."/></Reveal><Reveal delay={100}><IconCard icon={<MessageCircle/>} title="WhatsApp" text="Message us for appointment availability and clinic directions."/></Reveal><Reveal delay={200}><IconCard icon={<Video/>} title="Video consultation" text="Convenient for report reviews, follow-ups and outstation patients."/></Reveal></div><div className="mt-6 flex flex-wrap justify-center gap-3"><Button asChild size="lg" className="rounded-full"><a href="tel:+917995574432"><Phone/>Call now</a></Button><Button asChild size="lg" variant="outline" className="rounded-full"><a href="https://wa.me/917995574432"><MessageCircle/>WhatsApp</a></Button></div></div></section><section className="bg-blush py-20"><div className="mx-auto grid max-w-7xl items-stretch gap-10 px-5 lg:grid-cols-2"><Reveal><img src={clinicInterior} alt="Radiance Speciality Clinics reception" className="h-full min-h-[28rem] w-full rounded-lg object-cover shadow-glow-soft"/></Reveal><Reveal delay={120} className="rounded-lg bg-card p-8 shadow-card-soft"><p className="eyebrow">Visit the clinic</p><h2 className="mt-4 font-display text-3xl font-semibold text-wine">Radiance Speciality Clinics</h2><div className="mt-7 space-y-6 text-sm"><div className="flex gap-4"><MapPin className="h-5 w-5 text-rose"/><div><b className="text-foreground">Bachupally X Road</b><p className="mt-1 text-muted-foreground">Bachupally, Hyderabad, Telangana</p></div></div><div className="flex gap-4"><Clock className="h-5 w-5 text-rose"/><div><b className="text-foreground">Clinic hours</b><p className="mt-1 text-muted-foreground">Monday to Saturday · 9:00 AM – 9:00 PM</p></div></div><div className="flex gap-4"><CalendarDays className="h-5 w-5 text-rose"/><div><b className="text-foreground">Appointments recommended</b><p className="mt-1 text-muted-foreground">Call ahead to reduce your waiting time.</p></div></div></div><div className="mt-8 rounded-lg bg-blush p-5 text-sm leading-6 text-muted-foreground">For urgent medical symptoms, please contact your nearest emergency service rather than waiting for an online response.</div></Reveal></div></section></main>}