import { createFileRoute } from "@tanstack/react-router";
import { Baby, CheckCircle2, Flower2, HeartPulse, Microscope, Shield, Video } from "lucide-react";
import fertilityLab from "@/assets/fertility-lab.jpg";
import pregnancyCare from "@/assets/pregnancy-care.jpg";
import consultation from "@/assets/consultation.jpg";
import { AppointmentBand, IconCard, PageHero, SectionHeading } from "@/components/PageSections";
import { Reveal } from "@/components/Reveal";

export const Route=createFileRoute("/services")({head:()=>({meta:[{title:"Fertility, Pregnancy & Gynecology Services | Dr. Priyanka"},{name:"description",content:"Explore fertility, IVF, pregnancy, PCOS and comprehensive women's health services in Hyderabad."},{property:"og:title",content:"Women's Health Services | Dr. Priyanka Singh"},{property:"og:description",content:"Complete fertility, pregnancy and gynecology care in one trusted place."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/services"}]}),component:ServicesPage});
const groups=[{image:fertilityLab,label:"Fertility & reproductive medicine",title:"A considered path to parenthood",text:"Start with a complete evaluation, then move through treatment at a pace that fits your diagnosis and goals.",items:["Couple fertility evaluation","Ovulation induction and monitoring","IUI, IVF and ICSI guidance","Recurrent miscarriage support"]},{image:pregnancyCare,label:"Pregnancy & obstetrics",title:"Confident care through every trimester",text:"One connected plan from pre-conception through delivery and postnatal recovery, including close high-risk monitoring.",items:["Antenatal and pre-conception care","High-risk and multiple pregnancy care","Normal delivery and C-section planning","Postnatal and lactation support"]},{image:consultation,label:"Gynecology & wellness",title:"Long-term health, not quick fixes",text:"Understand the cause of symptoms and build a sustainable plan combining medical, lifestyle and surgical care when needed.",items:["PCOS, endometriosis and fibroids","Menstrual and hormonal disorders","Adolescent and menopause care","Laparoscopy and hysteroscopy"]}];
function ServicesPage(){return <main><PageHero eyebrow="Services" title="Complete care, thoughtfully connected." text="Specialist support across fertility, pregnancy and women’s health, with clear choices at every step." image={fertilityLab} imageAlt="Advanced fertility laboratory"/><section className="py-20"><div className="mx-auto max-w-7xl px-5"><SectionHeading eyebrow="Our expertise" title="Care for every life stage" text="Each plan is built around your needs—not a standard protocol."/><div className="mt-12 grid gap-6 md:grid-cols-3">{[{icon:<Microscope/>,title:"Fertility",text:"Evaluation, IUI, IVF, ICSI and fertility preservation guidance."},{icon:<Baby/>,title:"Pregnancy",text:"Antenatal, high-risk, delivery and postnatal support."},{icon:<Flower2/>,title:"Gynecology",text:"PCOS, endometriosis, menstrual health and minimally invasive care."}].map((x,i)=><Reveal key={x.title} delay={i*100}><IconCard {...x}/></Reveal>)}</div></div></section>{groups.map((g,i)=><section key={g.label} className={i%2?"bg-blush py-20":"py-20"}><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 lg:grid-cols-2"><Reveal className={i%2?"lg:order-2":""}><img src={g.image} alt={g.label} className="aspect-4/3 w-full rounded-lg object-cover shadow-glow-soft"/></Reveal><Reveal delay={120}><p className="eyebrow">{g.label}</p><h2 className="mt-4 font-display text-4xl font-semibold text-wine">{g.title}</h2><p className="mt-5 text-sm leading-7 text-muted-foreground">{g.text}</p><ul className="mt-7 grid gap-3">{g.items.map(x=><li key={x} className="flex gap-3 text-sm"><CheckCircle2 className="h-5 w-5 text-rose"/>{x}</li>)}</ul></Reveal></div></section>)}<section className="py-20"><div className="mx-auto max-w-7xl px-5"><SectionHeading eyebrow="Beyond the consultation" title="Support around your treatment"/><div className="mt-12 grid gap-6 md:grid-cols-3">{[{icon:<Video/>,title:"Video consultation",text:"Report reviews and follow-ups from home."},{icon:<HeartPulse/>,title:"Diagnostics",text:"Coordinated investigations and fertility monitoring."},{icon:<Shield/>,title:"Preventive care",text:"Screening, vaccination and wellness guidance."}].map((x,i)=><Reveal key={x.title} delay={i*100}><IconCard {...x}/></Reveal>)}</div></div></section><AppointmentBand title="Not sure which service you need?" text="Book a first consultation. Dr. Priyanka will listen, review your history and guide you to the right next step."/></main>}